name: Run swift-format
on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  swiftformat:
    name: "swift-format"
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Check out UBKit
        run: |
          git clone https://github.com/UbiqueInnovation/ubkit-ios __ubkit
          mv __ubkit/.swift-format .
      - name: Run swift-format
        run: swift format --in-place --parallel --recursive .
      - name: Delete UBKit
        run: |
          rm -rf __ubkit
          # Keep .swift-format in project
      - name: Configure git
        run: |
          git config --global --add safe.directory "$(pwd)"
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Add commit for swift-format file
        run: |
          git add .swift-format
          git commit -m "Update .swift-format"
      - name: Add commit for swift-format
        run: |
          git add *.swift
          git commit -m "[Generated] swift-format"
          # Store the commit hash for later use
          echo "FORMAT_COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Update git-blame-ignore-revs
        run: |
          # Add the formatting commit hash to .git-blame-ignore-revs
          echo "$FORMAT_COMMIT_HASH" >> .git-blame-ignore-revs
          git add .git-blame-ignore-revs
          git commit -m "Add swift-format commit to .git-blame-ignore-revs"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "generated/swift-format"
          delete-branch: true
          title: "[Generated] swift-format"
          body: "This action automatically runs swift-format on the project. Check the changes and merge them!"